[features]
seeds = false
skip-lint = false
[programs.localnet]
spl_token = "GbTWSq7vQKbXeHc9dMcugHK9wkogBLoSrpKGei42isfX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/khangnguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
